### ISSUE TITLE
Implement CI/CD

### ISSUE THREAD

**Issue by PedroHLC** [osdlyrics/osdlyrics#55]
It's a good feature to have in any open-source project.

**TODO:**
 * [ ] Decide platform (AppVeyor, Jenkins, GitLab, Travis)
 * [ ] Decide coding-style (It would be nice to have linters)
 * [ ] Implement initial version (with simple binary artifact release, lint)
 * [ ] Implement deployment to some common distro's packages.
 * [ ] Implement a few tests

**Comment by PedroHLC** [comment]
I forgot a few times to bump the version in [check-version.sh](https://github.com/osdlyrics/osdlyrics/blob/master/check-version.sh), so I should add the item:

- [ ] Bump version in `check-version.sh` and only-then publish tags.
